### ISSUE TITLE
Multiple Browsers with php/webdriver

### ISSUE THREAD

**Issue by daniel-watson** [facebook/php-webdriver#223]
Hi, I'm pretty new too Selenium in general but I would like to know if it is possible to run a PHPunit test with multiple browsers rather than having to set up identical tests with different browsers in the setUp() section?

I currently have all my tests working for my site with both the Chrome and Firefox drivers however I would rather not have identical tests bar the webdriver setup portion.

This is how I run the Chrome:
```
    $capabilitiesChrome = array(\WebDriverCapabilityType::BROWSER_NAME => 'chrome');
    $this->webDriver = \RemoteWebDriver::create('http://localhost:4444/wd/hub', $capabilitiesChrome );
```

Is there a way to store them in an array as in the the selenium2 webdriver like this:
```
   public static $browsers = [
        ['browserName' => 'firefox'],
        ['browserName' => 'chrome'],
        ['browserName' => 'iexplorer']  
    ];
```

Thanks in advance.

**Comment by gabrielpreston** [comment]
We've set ours up to be parameterized, so you can pass whatever browser you want from the command line. This works well for our Jenkins jobs because we can use whatever combination of OS/Browser/etc we wish and get to re-use the same exact script without having to edit anything. We originally thought about loading up the test with every version we wanted, but realized that wasn't the best way to go.

**Comment by daniel-watson** [comment]
Thank you for your reply. I believe I will set up a script to run the version I want from the command line. It should defiantly make it easier when I want to add new browsers or OS's.

**Comment by OndraM** [comment]
@daniel-watson You could also try [Steward](https://github.com/lmc-eu/steward), which comes with the CLI utility to handle exactly this case - run PHPUnit tests with browser passed as an option.
