### ISSUE TITLE
Need to disable SSL Certificate in firefox check for non ssl url

### ISSUE THREAD

**Issue by skaushikWebuy** [facebook/php-webdriver#406]
### What are you trying to achieve? (Expected behavior)
Need to disable SSL Certificate in firefox check for  invalid ssl urls as I am using my dev machine

### What do you get instead? (Actual behavior)
Your connection is not secure

The owner of example.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

### How could the issue be reproduced? (Steps to reproduce)

* Php-webdriver version: latest version
* PHP version:  5.6
* Selenium server version:  selenium-server-standalone-3.0.1.jar
* Operating system: Windows 10
* Browser used + version: Firefox 51

**Comment by OndraM** [comment]
@skaushikWebuy Hi, this is an issue of Geckodriver - Selenium implementation in Firefox 48+ https://github.com/mozilla/geckodriver/issues/93  / https://bugzilla.mozilla.org/show_bug.cgi?id=1103196

The issue appears to be fixed in Firefox Aurora, so it should be part of Firefox 53. You can either wait for the version 53, or use the Aurora version or you can downgrade to Firefox ESR (and use it together with Selenium 2.53.1).

Also related to https://github.com/facebook/php-webdriver/issues/384

**Comment by skaushikWebuy** [comment]
Please suggest sample code

**Comment by gabrielpreston** [comment]
According to @OndraM, this isn't a code issue, this is a software issue. You need to change the versions of Selenium and Firefox that you are using.
