### ISSUE TITLE
How can I save an image shown by such as img element in html to file in my local file system?

### ISSUE THREAD

**Issue by sooglejay** [facebook/php-webdriver#452]
### What are you trying to achieve? (Expected behavior)

I want to save a picture in html such as: http://www.63si.com.cn:8888/lswtqt/CaptchaImg
### How could the issue be reproduced? (Steps to reproduce)

```php

        $this->validateNumberElem = $this->webDriver->findElement(WebDriverBy::id('captcha_gr'));
        $this->webDriver->wait(3);
        $url = $this->validateNumberElem->getText();
        $curl = curl_init($url);
        $filename = date("Ymdhis") . ".jpg";
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        $imageData = curl_exec($curl);
        curl_close($curl);
        $tp = @fopen($filename, 'a');
        fwrite($tp, $imageData);
        fclose($tp);

```

### Details

* Php-webdriver version: latest
* PHP version: latest
* Selenium server version: latest
* Operating system: MacOSX latest
* Browser used + version: Chrome  latest

**Comment by OndraM** [comment]
Hi, so the issue is the content of the target URL always change? So the download file using php approach wont help you?

Is so, I would try taking screenshot of the actual rendered element. See eg. https://stackoverflow.com/questions/13832322/how-to-capture-the-screenshot-of-a-specific-element-rather-than-entire-page-usin

**Comment by sooglejay** [comment]
thanks a lot @OndraM
