### ISSUE TITLE
Wrong $raw_element structure when using FireFox with RemoteWebDriver

### ISSUE THREAD

**Issue by itaibh** [facebook/php-webdriver#485]
### What are you trying to achieve? (Expected behavior)
Find an element on FireFox using RemoteWebDriver.

### What do you get instead? (Actual behavior)
I get an error: 

    Undefined index: ELEMENT

### How could the issue be reproduced? (Steps to reproduce)
I initialize a RemoteWebDriver using `DesiredCapabilities::firefox();`
When the test runs on its own everything seems fine. But when it runs after another test in the suit, `$raw_element` has a different structure in `RemoteWebDriver.php : findElement(WebDriverBy $by)`

### Details

* Php-webdriver version: ^1.4.1
* PHP version: 7.0
* Selenium server version: 3.6.0
* Operating system: Windows 10
* Browser used + version: Firefox 56.0.1

**Comment by OndraM** [comment]
Hi @itaibh , this is caused by #469 .

To solve the issue for now, you could either use Chrome (which works pretty well), or Selenium 3.4, or you must enable the protocol translating in Selenium (as mentioned in #469), using Selenium option `-enablePassThrough false`, like ` java -jar selenium-server-standalone-3.6.0.jar -enablePassThrough false`.

Sorry for inconvenience :).
