### ISSUE TITLE
How to run webdriver parallel in Selenium Grid

### ISSUE THREAD

**Issue by jacksontong** [facebook/php-webdriver#491]
### What are you trying to achieve? (Expected behavior)
Example I have an array of urls
```php
$urls = [
    'http://google.com',
    'http://facebook.com',
];
```
I'm be able to setup the [Hub](https://hub.docker.com/r/selenium/hub/) and [Node](https://hub.docker.com/r/selenium/node-chrome/) through Docker. How can I perform my task parallel instead of one by one in a loop?

```php
foreach($urls as $url) {
    $driver->get($url);
}
```

* Php-webdriver version: latest
* PHP version: 7.1

**Comment by OndraM** [comment]
Hi, PHP is by default single-threaded.

If you want parallelism, you can for example leverage React PHP and encapsulate the request to promises: https://reactphp.org/ (but each request would have to have its own $driver instance, otherwise you would control the same browser window).

And If you want parallel execution of your test, have a look eg. on https://github.com/lmc-eu/steward /
