### ISSUE TITLE
Curl error thrown f or http POST

### ISSUE THREAD

**Issue by imsheng** [facebook/php-webdriver#520]
### How could the issue be reproduced? (Steps to reproduce)
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown f
or http POST to /session/9756a112-36bf-4999-bae7-59d8f506c253/url with params: {"url":"http:\/\/gam
e.hao123.com"}
Operation timed out after 30000 milliseconds with 0 bytes received in ...

```php
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::htmlUnit();
$capabilities->setJavascriptEnabled(false);
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
//or
//$driver = RemoteWebDriver::create($host, $capabilities, 5000,5000);
$driver->get('http://game.hao123.com');
$html =$driver->getPageSource();
```

### Details

* Php-webdriver version: 1.5
* PHP version:  7.1.7(cli)
* Selenium server version: 3.8.1
* Operating system: win 10
* Browser used + version:  htmlUnit ?

**Comment by tabuna** [comment]
I experience the same difficulties.

**Comment by AtricoSoftware** [comment]
Same problem
Using example php file with...

$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::chrome();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);

**Stack trace**
#1 /.../example.php(12): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#2 {main}
  thrown in /.../vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 286
java.lang.RuntimeException: org.seleniumhq.jetty9.io.EofException
        at org.openqa.selenium.remote.server.ServletResponseWrappingHttpResponse.setContent(ServletResponseWrappingHttpResponse.java:91)
        at org.openqa.selenium.remote.server.ServletResponseWrappingHttpResponse.setContent(ServletResponseWrappingHttpResponse.java:83)
        at org.openqa.selenium.remote.server.commandhandler.ExceptionHandler.execute(ExceptionHandler.java:96)
        at org.openqa.selenium.remote.server.WebDriverServlet.handle(WebDriverServlet.java:258)
        at org.openqa.selenium.remote.server.WebDriverServlet.doPost(WebDriverServlet.java:161)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)


**Environment**
Windows 10 (using bash)
php v7.1.14
selenium v3.9.1
chromedriver v2.35.528139

**Comment by OndraM** [comment]
@AtricoSoftware Hi, this seems like an unrelated problem to the original report - it is different browser and different error. Could you please open separate issue and provide also output of Selenium server, command you used to start Selenium and also version of Chome you used? Thanks!

**Comment by klimart** [comment]
I'm experiencing this issue after driver multiple starts and quits. It's not consistent but some dozens of loops (start driver, tests run, driver quit) runs smoothly and then on some loop this error appears on start.
selenium-server-standalone : 3.8.1
chromedriver: 2.35
Linux, Ubuntu 16.4, server edition
Google Chrome 64.0.3282.186

**Comment by mb0000** [comment]
I have been experiencing the time out problem too.
Environment:
- Windows 7 Ultimate (ver -> 6.1.7601)
- PHP 7.2.4
- Selenium 3.141.5
- JVM 1.8.0_191-b12
- chromeDriver.exe 2.43.600210

Symptom:
ONLY WebDriver POST requests time out and then ONLY when the request is a .../url - in other words when the browser is being asked to fetch a page. Other POST requests (to set Selenium or ChromeDriver "parameters") work.

The analysis of the timeout problem I've been experiencing has led me to the following conclusions:
- With some features of my anti-virus enabled (firewall-like), I could reliably reproduce the "problem". Disabling those features restricted the problem to relate to how Selenium was "forked" (see below). So that might explain some people's time outs, but not mine.
- When starting PHP from a Windows command prompt directly (e.g. php test.php or even START /B php test.php) did not reproduce the time out.
- When starting PHP in the following arcane way DID reproduce the problem: visit a local web page (served by Apache 2.4.33) which runs a PHP script, which itself uses proc_open to spawn a CMD.EXE shell to run the same command line PHP script test.php from within a .cmd file. (I use this complicated method so that I can start PHP scripts that take considerably longer to execute than max_execution_time and may be initiated remotely)
- using Wireshark, I can see the Selenium POST /url request is passed all the way to Chrome as Chrome does make the GET to the remote website, so the timeout would appear to be caused by one of the mechanisms of Chrome <-> ChromeDriver.exe interaction, ChromeDriver.exe <-> Selenium.exe interaction. I "confirmed" this by wrapping the WebDriver ->get() call in an Exception handler and then following up with calls to access the page source or logs, both of which worked and gave back the expected results (implying that Chrome had fetched the page and that even after the time out the Chrome - ChromeDriver - Selenium - PHP chain was still working).
- I think in my situation, the issue is related to how Apache threads influence spawning of PHP proc_open processes (or exec) and TCP time out handling, along with JVM sandboxing of Selenium - I can't see how, but I can't find a suitable explanation (or devote much more time to the analysis - I am working on a workaround that avoids use of Selenium and uses ChromeDriver directly).

Hope this helps someone!

**Comment by mb0000** [comment]
I have an update to my post of 2018-11-30.
Upon further investigation, I believe this is now either a bug (or undesirable consequence of the exception handling under Windows) in exception handling in `ChromeDriver.exe`.
In my environment, I can reproduce the time out occurs when doing a `driver->get()` from a web page that causes WebDriver to emit an UncaughtReference error for "browser not defined" and when ChromeDriver has been forked in the background. I have tried forking using various Windows tools - `wmic`, `CMD.EXE start /b`, `schtasks` - the essence of it is, if the `chromedriver.exe` process does not have a Window in which to emit its output (it doesn't seem to matter if having redirected STDOUT and STDERR, nor having set a log-file via `--log-path`) AND at least the UncaughtReference exception (and possibly others) occurs, then the time out will occur. By turning on full logging for ChromeDriver, it logs an event `[<timestamp>][DEBUG]: DevTools WebSocket Event: Runtime.exceptionThrown` for this exception. I have replaced the PHP curl calls used in WebDriver either with non-webdriver calls replicating the communication sequence (PHP <-> chromedriver) or with `file_get_contents` calls with suitable context settings. In both cases, the time out occurred, which is why I don't consider this issue to be in PHP-WebDriver

Anyone know how to raise a bug report with the chromedriver project?
