### ISSUE TITLE
Facebook\WebDriver\Exception\UnknownCommandException

### ISSUE THREAD

**Issue by SagarNaliyapara** [facebook/php-webdriver#636]
### What are i'm trying to achieve?
I'm trying to run Codeship build

### What do I get instead? (Actual behavior)
```
Facebook\WebDriver\Exception\UnknownCommandException: POST /session/0a263573c608002afc74fa6b59aeb0d0/element//clear
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'f4107bb89fa3', ip: '172.25.1.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1013-aws', java.version: '1.8.0_212'
Driver info: driver.version: unknown
```

**Comment by olleharstedt** [comment]
Was this solved? How?

**Comment by SagarNaliyapara** [comment]
@olleharstedt It was versioning issue with browser, What error you are facing?

**Comment by olleharstedt** [comment]
We are facing lots of UnknownCommandException after updating to latest Firefox, Selenium and geckodriver. Example:

```
Facebook\WebDriver\Exception\UnknownCommandException: POST /session/ec33262e-5a7d-4acf-ab2c-f98e434c661d/element/value
```

The PHP code:

```
$userNameField->sendKeys($userName);
```

$userNameField is not null. This line used to work with Selenium 3.7 and geckodriver 23.

Is there a list for which versions are compatible with what drivers?

**Comment by olleharstedt** [comment]
We're now testing with Selenium 3.14 and geckodriver 25.

**Comment by olleharstedt** [comment]
Looks like the `:id` in the URL command is not populated. Or, it's populated with NULL, which creates an invalid command.

**Comment by olleharstedt** [comment]
Problem solved by making sure the argument `-enablePassThrough false` is set.

**Comment by elicoten** [comment]
@olleharstedt Please could you elaborate a bit more on how you set this option?

I tried to run Selenium server version `3.141.59`, with the `-enablePassThrough false` option in the terminal and I encountered the same problem as described [on this StackOverflow question](https://stackoverflow.com/questions/48682811/enablepassthrough-not-available-for-selenium-server-3-9-1).

The answer there states that the option has been removed since Selenium version 3.9 but I noticed that you're using the same version as me and you managed to get it to work?

**Comment by olleharstedt** [comment]
@elicoten No, we backed to an earlier version of selenium, 3.7.1.
