### ISSUE TITLE
BrowserStack does not accept w3c key in chromeOptions

### ISSUE THREAD

**Issue by williamdes** [facebook/php-webdriver#644]
### What are you trying to achieve? 
Run tests like in 4.6

### What do you get instead? (Actual behavior)
An exception:
`The property '#/' contains additional properties ["w3c"] outside of the schema when none are allowed in chromeOptions`

### How could the issue be reproduced? (Steps to reproduce)
https://github.com/phpmyadmin/phpmyadmin/issues/15324

### Details

* Php-webdriver version: 4.7.0
* PHP version: 7.2
* Selenium server version: ? (browserstack) 
* Operating system: linux
* Browser used + version: Google Chrome

**Comment by williamdes** [comment]
cc @OndraM

**Comment by Trawais** [comment]
Just additional info: This is problem mainly (and only) for BrowserStack provider. I assume there is some modification of protocol on BrowserStack side.

**Comment by OndraM** [comment]
Yes, BrowserStack for some reason does not accept "w3c" key inside "chromeOptions" (or "goog:chromeOptions" capability. 

There is in no reason for this - content of [vendor specific](https://w3c.github.io/webdriver/#dfn-extension-capability) capabilities does not have any limitation according to the standard. Please contact BrowserStack support and ask them to fix (ie. relax) their schema validation.

But in order to not break things for you, I implemented workaround - if your remote selenium server contains "browserstack" as part of its URL, the w3c capability for chrome is not triggered. However, this workaround may not work on 100%, its kind of dirty hack, and won't be kept permanently. So I urge you to contact browserstack and let them know about the issue in their schema validation ASAP.

**Comment by williamdes** [comment]
> So I urge you to contact browserstack

Done
