### ISSUE TITLE
Problem using chrome and proxy

### ISSUE THREAD

**Issue by ingen2** [facebook/php-webdriver#661]
Hi 

I try to set proxy with chrome driver with this method:
https://github.com/facebook/php-webdriver/wiki/HowTo-Work-with-proxy
but I got error.
how to set http proxy(with username and password) on chrome driver?

my code:

       `$capabilities->setCapability(
                        WebDriverCapabilityType::PROXY,
                        [
                            'proxyType' => 'manual',
                            'httpProxy' => 'http://proxy.com:8200',
                            'sslProxy' => 'http://proxy.com:8200',
                            'ftpProxy' => 'http://proxy.com:8200',
                            'socksUsername' => 'musernameer',
                            'socksPassword' => 'vuqweqwe234t'
                        ]
         );`

**Comment by OndraM** [comment]
Hi @ingen2 , sorry for late reply. I'm closing this for now because there hasn't been any activity for a while and the issue might be already resolved. But if it still persist, please don't hesitate to open a new issue. However please fill the issue template which is provided when creating new issue - otherwise we might not be able to help you.

**Comment by ingen2** [comment]
My problem solved with this solution: 
https://github.com/RobinDev/Selenium-Chrome-HTTP-Private-Proxy
