### ISSUE TITLE
Entering text to datetime-local input

### ISSUE THREAD

**Issue by romaricdrigon** [facebook/php-webdriver#709]
### What are you trying to achieve? (Expected behavior)

I'm trying to set a `<input type="datetime-local">`. I can't find how to correctly set it, using `sendKey`.  Standard HTML formats are not supported, and I tried to emulate what I type on my keyboard, no luck either.

It looks like date and time are mixed.
I tried those format:
```php
"2020-01-15 18:00"
"2020-01-15T18:00"
"15/01/2020 18:00"
"15/01/2020 1800"
"15/01/2020\t1800"
```

### What do you get instead? (Actual behavior)

I'm getting scrambled input, such as this:
![image](https://user-images.githubusercontent.com/919405/70608282-25eba780-1c00-11ea-8c2c-36e4a4318646.png)

### Details

* Php-webdriver version:  1.7
* PHP version: 7.4
* Selenium server version: using Chromedriver directly
* Operating system: macOS, fr locale
* Browser used + version: Chrome 78

**Comment by andrewnicols** [comment]
I hit the same issue in my new mink driver:

https://github.com/andrewnicols/MinkFacebookWebDriver/blob/master/src/Driver/FacebookWebDriver.php

I ‘solved’ it with a hack and an intention to raise a bug against the specification which I have not yet done.

**Comment by OndraM** [comment]
True, this seems like something not covered by the specs. It is also not yet supported by [some browsers](https://caniuse.com/#feat=input-datetime) - not Safari nor Firefox does support it.

Have you seen this article? https://www.guru99.com/handling-date-time-picker-using-selenium.html

My other workaround would be entering the data via javascript - either by manipulating the input value, or to change the input type to text (what is the same as if you use the input in some of the browsers not supporting it).

So this is something not related to php-webdriver? So I guess we can close the issue here and if you report it to W3C WebDriver you can link it here?

**Comment by andrewnicols** [comment]
Will read that article!

My hack was to use is to set the value.

**Comment by romaricdrigon** [comment]
@OndraM I did exactly that, I'm using JS to set the value.

Indeed it seems it is not specific to php-webdriver now I read your messages. I will open an issue on w3c/webdriver and close that one after.

**Comment by andrewnicols** [comment]
Raised against the spec in https://github.com/w3c/webdriver/issues/1470.

Please feel free to add further information to this issue.

**Comment by andrewnicols** [comment]
I've now raised a bug against chromedriver too: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3274
