### ISSUE TITLE
proxy issue: JSON decoding of remote response failed.

### ISSUE THREAD

**Issue by AhmadWaleed** [facebook/php-webdriver#729]
### What are you trying to achieve? (Expected behavior)
I am using a symfony/panther for webscrapping and trying to use chrome web-driver with a proxy server 
### What do you get instead? (Actual behavior)
I get this error
```
JSON decoding of remote response failed.
Error code: 4
The response: '<html><body><b>Http/1.1 Gateway Timeout</b></body> </html>
```
### How could the issue be reproduced? (Steps to reproduce)

```php
        $capabilities = DesiredCapabilities::chrome();
        if ($this->arguments) {
            $chromeOptions = new ChromeOptions();
            $chromeOptions->addArguments($this->arguments);
            $capabilities->setCapability(ChromeOptions::CAPABILITY, $chromeOptions);
            if (isset($_SERVER['PANTHER_CHROME_BINARY'])) {
                $chromeOptions->setBinary($_SERVER['PANTHER_CHROME_BINARY']);
            }
        }

//        return RemoteWebDriver::create($url, $capabilities);
        return RemoteWebDriver::create(
            $url,
            $capabilities,
            null,
            null,
            'http://209.90.63.108:80'
        );
```

### Details

* Php-webdriver version: 1.7.1
* PHP version: 7.4
* Selenium server version: 
* Operating system: ubuntu 18.04
* Browser used + version: Google Chrome 78.0.3904.97

**Comment by andrewnicols** [comment]
Hi @AhmadWaleed ,

Can you confirm that the proxy is correctly set, and working? It would also be good if you could provide the chromedriver logs. You can obtain these by specifying `--verbose --log-path=/tmp/chromedriver.log` to chromedriver.

**Comment by AhmadWaleed** [comment]
@andrewnicols thanks for the reply but i made it work with passing following configuration.

```php
$this->client = Client::createChromeClient(null, [
            '--window-size=1200,1100',
            "--proxy-server=http://ip:port",
            '--headless',
            "--disable-gpu",
]);
```

i think previously proxy server i was using doesn't support https (i was try to visit https page) and i was also missing windows-size argument.

**Comment by OndraM** [comment]
I believe there are being mixed two different things:

1) Proxy server used for connection to Selenium server (Chromedriver). This is what the fifth argument of `RemoteWebDriver::create()` is for. This is usable if the Selenium remote runs behind a proxy, ie. you cannot connect to it directly. This means your script does not connect to Selenium/Chromedriver, but to the proxy first. However I believe this is not what you needed and wanted and it also causes the error, because there obviously hasn't been a Chromedriver running on the IP.

2) Proxy server which Chrome use when accessing webpages. It could be set be either by [capabilities](https://github.com/facebook/php-webdriver/wiki/HowTo-Work-with-proxy) or by CLI argument of Chrome which you used.
